///*;;
// * To change this license header, choose License Headers in Project Properties.
// * To change this template file, choose Tools | Templates
// * and open the template in the editor.
// */
//package duelofarmslash;
//
//import java.awt.Rectangle;
//import java.awt.event.ActionEvent;
//import java.awt.event.ActionListener;
//
//import javax.swing.ImageIcon;
//import javax.swing.JButton;
//import javax.swing.JFrame;
//import javax.swing.JMenu;
//import javax.swing.JMenuBar;
//import javax.swing.JMenuItem;
//import javax.swing.JOptionPane;
//import javax.swing.JPanel;
//
///**
// *
// * @author kire
// */
//public class TelaPrincipal extends JFrame {
//    INTERFACE2 frameAssociado;
//    protected AtorJogador ator;
//
//    public TelaPrincipal(AtorJogador ator) {
//        setTitle("Duelo - Farm and Slash");
//        this.ator = ator;
//        initComponents();
//
//    }
////
////    public TelaPrincipal(INTERFACE2 i2) {
////        frameAssociado = i2;
////        initComponents();
////
////    }
//
//    public void notificar(String msg) {
//
//        JOptionPane.showConfirmDialog(this, msg, "Atenção", JOptionPane.DEFAULT_OPTION, JOptionPane.PLAIN_MESSAGE);
//            //JOptionPane.showMessageDialog(null, msg);
//    }
//
//
//    public String solicitar(String msg, String def) {
//            return JOptionPane.showInputDialog(msg, def);
//    }
//
//
//    /**
//     * This method is called from within the constructor to initialize the form.
//     * WARNING: Do NOT modify this code. The content of this method is always
//     * regenerated by the Form Editor.
//     */
//    @SuppressWarnings("unchecked")
//    // <editor-fold defaultstate="collapsed" desc="Generated Code">
//    private void initComponents() {
//
//        jMenuBar1 = new javax.swing.JMenuBar();
//        jMenu1 = new javax.swing.JMenu();
//        iniciarPartida = new javax.swing.JMenuItem();
//        conectar = new javax.swing.JMenuItem();
//        desconectar = new javax.swing.JMenuItem();
//        jMenu1.setText("Menu");
//
//        // INICIAR PARTIDA //
//        iniciarPartida.setText("Iniciar partida");
//        iniciarPartida.addActionListener(new java.awt.event.ActionListener(){
//        public void actionPerformed(java.awt.event.ActionEvent e) {
//                try {
//
//                    ator.IniciarPartida();
//
//                        //if (ator.getPartida().informaSePartidaEmAndamento()) {
//                        //      reiniciar.setEnabled(true);
//                         iniciarPartida.setEnabled(false);
//                        //}
//
//                     } catch (Exception e1) {
//                        System.out.println("ex");
//                        notificar(e1.getMessage());
//                        e1.printStackTrace();
//            }
//        }
//        });
//        jMenu1.add(iniciarPartida);
//        // CONECTAR //
//
//        conectar.setText("Conectar");
//        conectar.addActionListener(new ActionListener(){
//	public void actionPerformed(java.awt.event.ActionEvent e) {
//            try {
//                    String servidor = solicitar("Insira o servidor:", "localhost");
//                    String nomeJogador = solicitar("Insira seu nome:", null);
//
//                    ator.conectar(nomeJogador, servidor);
//                    iniciarPartida.setEnabled(true);
//                    desconectar.setEnabled(true);
//                    conectar.setEnabled(false);
//                    notificar("A conexao foi estabelecida com sucesso.");
//            } catch (Exception ex) {
//                    notificar(ex.getMessage());
//                    ex.printStackTrace();
//            }
//        }
//        });
//        jMenu1.add(conectar);
//        // DESCONECTAR //
//
//
//        desconectar.setText("Desconectar");
//        desconectar.addActionListener(new ActionListener(){
//        public void actionPerformed(java.awt.event.ActionEvent e) {
//            try {
//                    ator.desconectar();
//                    desconectar.setEnabled(false);
//                    conectar.setEnabled(true);
//                 //   reiniciar.setEnabled(false);
//                    iniciarPartida.setEnabled(false);
//                    notificar("Voce se desconectou da partida. A conexao foi encerrada");
//            } catch (Exception ex) {
//                    notificar(ex.getMessage());
//                    ex.printStackTrace();
//            }
//    }
//        });
//        jMenu1.add(desconectar);
//
//        jMenuBar1.add(jMenu1);
//
//        setJMenuBar(jMenuBar1);
//        jButton1 = new javax.swing.JButton();
//        jButton2 = new javax.swing.JButton();
//        jButton3 = new javax.swing.JButton();
//        jProgressBar1 = new javax.swing.JProgressBar();
//        jProgressBar2 = new javax.swing.JProgressBar();
//        jPanel1 = new javax.swing.JPanel();
//        jLabel1 = new javax.swing.JLabel();
//        jLabel2 = new javax.swing.JLabel();
//        jLabel3 = new javax.swing.JLabel();
//        jLabel4 = new javax.swing.JLabel();
//        jLabel7 = new javax.swing.JLabel();
//        jLabel5 = new javax.swing.JLabel();
//        jLabel6 = new javax.swing.JLabel();
//        jButton5 = new javax.swing.JButton();
//
//        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
//
//        jButton1.setText("Desistir");
//
//        jButton2.setText("Loja");
//
//        jButton3.setText("Ataque");
//        jButton3.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                jButton3ActionPerformed(evt);
//            }
//        });
//
//        jProgressBar2.setBackground(new java.awt.Color(245, 247, 245));
//
//        jLabel1.setText("Atributos");
//
//        jLabel2.setText("HP : 100");
//
//        jLabel3.setText("ATK: 10");
//
//        jLabel4.setText("DEF: 0%");
//
//        jLabel7.setText("Creditos: 0");
//
//        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
//        jPanel1.setLayout(jPanel1Layout);
//        jPanel1Layout.setHorizontalGroup(
//            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(jPanel1Layout.createSequentialGroup()
//                .addGap(20, 20, 20)
//                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                    .addGroup(jPanel1Layout.createSequentialGroup()
//                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                            .addComponent(jLabel4)
//                            .addComponent(jLabel3))
//                        .addContainerGap(31, Short.MAX_VALUE))
//                    .addGroup(jPanel1Layout.createSequentialGroup()
//                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                            .addComponent(jLabel1)
//                            .addGroup(jPanel1Layout.createSequentialGroup()
//                                .addGap(2, 2, 2)
//                                .addComponent(jLabel2)))
//                        .addGap(0, 0, Short.MAX_VALUE))))
//            .addGroup(jPanel1Layout.createSequentialGroup()
//                .addContainerGap()
//                .addComponent(jLabel7)
//                .addGap(0, 0, Short.MAX_VALUE))
//        );
//        jPanel1Layout.setVerticalGroup(
//            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(jPanel1Layout.createSequentialGroup()
//                .addGap(28, 28, 28)
//                .addComponent(jLabel1)
//                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                .addComponent(jLabel2)
//                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                .addComponent(jLabel3)
//                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                .addComponent(jLabel4)
//                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                .addComponent(jLabel7))
//        );
//
//        jLabel5.setText("Vida");
//
//        jLabel6.setText("Oponente");
//
//        jButton5.setText("Mudar (Provisório)");
//        jButton5.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                jButton5ActionPerformed(evt);
//            }
//        });
//
//        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
//        getContentPane().setLayout(layout);
//        layout.setHorizontalGroup(
//            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
//            .addGroup(layout.createSequentialGroup()
//                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                    .addGroup(layout.createSequentialGroup()
//                        .addContainerGap()
//                        .addComponent(jButton5)
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                        .addComponent(jLabel5)
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                        .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
//                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
//                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
//                                .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)
//                                .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
//                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
//                                .addComponent(jLabel6)
//                                .addGap(18, 18, 18)
//                                .addComponent(jProgressBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))))
//                .addContainerGap())
//        );
//        layout.setVerticalGroup(
//            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
//                .addContainerGap()
//                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
//                    .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                        .addComponent(jLabel5)
//                        .addComponent(jButton5)))
//                .addGap(11, 11, 11)
//                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                    .addGroup(layout.createSequentialGroup()
//                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
//                            .addComponent(jProgressBar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                            .addComponent(jLabel6))
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
//                        .addComponent(jButton3)
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                        .addComponent(jButton2)
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                        .addComponent(jButton1))
//                    .addGroup(layout.createSequentialGroup()
//                        .addGap(3, 3, 3)
//                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
//                .addContainerGap())
//        );
//
//        pack();
//    }    // </editor-fold>
//
//    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
//        // TODO add your handling code here:
//    }
//
//    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {
//        // TODO add your handling code here:
//        frameAssociado.setVisible(true);
//        this.setVisible(false);
//    }
//
//
//
//    // Variables declaration - do not modify
//    private javax.swing.JButton jButton1;
//    private javax.swing.JButton jButton2;
//    private javax.swing.JButton jButton3;
//    private javax.swing.JButton jButton5;
//    private javax.swing.JLabel jLabel1;
//    private javax.swing.JLabel jLabel2;
//    private javax.swing.JLabel jLabel3;
//    private javax.swing.JLabel jLabel4;
//    private javax.swing.JLabel jLabel5;
//    private javax.swing.JLabel jLabel6;
//    private javax.swing.JLabel jLabel7;
//    private javax.swing.JPanel jPanel1;
//    private javax.swing.JProgressBar jProgressBar1;
//    private javax.swing.JProgressBar jProgressBar2;
//    private javax.swing.JMenu jMenu1;
//    private javax.swing.JMenuBar jMenuBar1;
//    javax.swing.JMenuItem iniciarPartida;
//    javax.swing.JMenuItem conectar;
//    private javax.swing.JMenuItem desconectar;
//    private javax.swing.JMenuItem jMenuItem4;
//    // End of variables declaration
//}
//
///*
// * To change this license header, choose License Headers in Project Properties.
// * To change this template file, choose Tools | Templates
// * and open the template in the editor.
// */
//package duelofarmslash;
//
//import java.awt.event.ActionListener;
//import javax.swing.JOptionPane;
//import java.awt.Rectangle;
//import java.awt.event.ActionEvent;
//import java.awt.event.ActionListener;
//
//import javax.swing.ImageIcon;
//import javax.swing.JButton;
//import javax.swing.JFrame;
//import javax.swing.JMenu;
//import javax.swing.JMenuBar;
//import javax.swing.JMenuItem;
//import javax.swing.JOptionPane;
//import javax.swing.JPanel;
///**
// *
// * @author kire
// */
//public class TelaPrincipalDuel extends javax.swing.JFrame {
//    protected AtorJogador ator;
//
//    /**
//     * Creates new form TelaPrincipalDuel
//     */
//    public TelaPrincipalDuel(AtorJogador ator) {
//        setTitle("Duelo - Farm and Slash");
//        this.ator = ator;
//        initComponents();
//    }
//
////    private TelaPrincipalDuel() {
////        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
////    }
//
//    public void notificar(String msg) {
//
//        JOptionPane.showConfirmDialog(this, msg, "Atenção", JOptionPane.DEFAULT_OPTION, JOptionPane.PLAIN_MESSAGE);
//            //JOptionPane.showMessageDialog(null, msg);
//    }
//
//
//    public String solicitar(String msg, String def) {
//            return JOptionPane.showInputDialog(msg, def);
//    }
//
//    /**
//     * This method is called from within the constructor to initialize the form.
//     * WARNING: Do NOT modify this code. The content of this method is always
//     * regenerated by the Form Editor.
//     */
//    @SuppressWarnings("unchecked")
//    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
//    private void initComponents() {
//
//        jMenu3 = new javax.swing.JMenu();
//        AtacarButton = new javax.swing.JButton();
//        FarmarButton = new javax.swing.JButton();
//        LojaButton = new javax.swing.JButton();
//        DesistirButton = new javax.swing.JButton();
//        VidaBarra1 = new javax.swing.JProgressBar();
//        VidaBarra2 = new javax.swing.JProgressBar();
//        Status = new javax.swing.JLabel();
//        Ataque = new javax.swing.JLabel();
//        Block = new javax.swing.JLabel();
//        Creditos = new javax.swing.JLabel();
//        SuaVidaText = new javax.swing.JLabel();
//        VidaOponenteText = new javax.swing.JLabel();
//        Perso1 = new javax.swing.JLabel();
//        Perso2 = new javax.swing.JLabel();
//        jMenuBar1 = new javax.swing.JMenuBar();
//        Menu = new javax.swing.JMenu();
//        iniciarPartida = new javax.swing.JMenuItem();
//        DesconectarItem = new javax.swing.JMenuItem();
//        ServidorItem = new javax.swing.JMenuItem();
//
//        jMenu3.setText("jMenu3");
//
//        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
//
//        AtacarButton.setText("Atacar");
//        AtacarButton.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                AtacarButtonActionPerformed(evt);
//            }
//        });
//
//        FarmarButton.setText("Farmar");
//        FarmarButton.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                FarmarButtonActionPerformed(evt);
//            }
//        });
//
//        LojaButton.setText("Loja");
//        LojaButton.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                LojaButtonActionPerformed(evt);
//            }
//        });
//
//        DesistirButton.setText("Desistir");
//
//        Status.setText("Status");
//
//        Ataque.setText("Ataque:");
//
//        Block.setText("Block:");
//
//        Creditos.setText("Creditos:");
//
//        SuaVidaText.setText("Sua vida:");
//
//        VidaOponenteText.setText("Oponente:");
//
//        Perso1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/duelofarmslash/person1.gif"))); // NOI18N
//
//        Perso2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/duelofarmslash/person2.gif"))); // NOI18N
//
//        Menu.setText("Menu");
//        // Iniciar partida
//        iniciarPartida.setText("Iniciar partida");
//        iniciarPartida.addActionListener(new java.awt.event.ActionListener(){
//        public void actionPerformed(java.awt.event.ActionEvent e) {
//                try {
//
//                    ator.IniciarPartida();
//
//                        //if (ator.getPartida().informaSePartidaEmAndamento()) {
//                        //      reiniciar.setEnabled(true);
//                         iniciarPartida.setEnabled(false);
//                        //}
//
//                     } catch (Exception e1) {
//                        System.out.println("ex");
//                        notificar(e1.getMessage());
//                        e1.printStackTrace();
//            }
//        }
//        });
//        Menu.add(iniciarPartida);
//
//        DesconectarItem.setText("Desconectar");
//        DesconectarItem.addActionListener(new ActionListener(){
//        public void actionPerformed(java.awt.event.ActionEvent e) {
//            try {
//                    ator.desconectar();
//                    DesconectarItem.setEnabled(false);
//                    ServidorItem.setEnabled(true);
//                 //   reiniciar.setEnabled(false);
//                    iniciarPartida.setEnabled(false);
//                    notificar("Voce se desconectou da partida. A conexao foi encerrada");
//            } catch (Exception ex) {
//                    notificar(ex.getMessage());
//                    ex.printStackTrace();
//            }
//      }
//      });
//        Menu.add(DesconectarItem);
//
//        ServidorItem.setText("Conectar ao servidor");
//        ServidorItem.addActionListener(new ActionListener(){
//	         public void actionPerformed(java.awt.event.ActionEvent e) {
//            try {
//                    String servidor = solicitar("Insira o servidor:", "localhost");
//                    String nomeJogador = solicitar("Insira seu nome:", null);
//                    ator.conectar(nomeJogador, servidor);
//                    iniciarPartida.setEnabled(true);
//                    DesconectarItem.setEnabled(true);
//                    ServidorItem.setEnabled(false);
//                    notificar("A conexao foi estabelecida com sucesso.");
//            } catch (Exception ex) {
//                    notificar(ex.getMessage());
//                    ex.printStackTrace();
//            }
//        }
//        });
//        Menu.add(ServidorItem);
//
//        jMenuBar1.add(Menu);
//
//        setJMenuBar(jMenuBar1);
//
//        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
//        getContentPane().setLayout(layout);
//        layout.setHorizontalGroup(
//            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(layout.createSequentialGroup()
//                .addContainerGap()
//                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                    .addGroup(layout.createSequentialGroup()
//                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
//                            .addGroup(layout.createSequentialGroup()
//                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                                    .addComponent(Status)
//                                    .addComponent(Ataque)
//                                    .addComponent(Block)
//                                    .addComponent(Creditos))
//                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
//                                    .addComponent(DesistirButton, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
//                                    .addComponent(LojaButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                                    .addComponent(AtacarButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                                    .addComponent(FarmarButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
//                            .addGroup(layout.createSequentialGroup()
//                                .addComponent(SuaVidaText)
//                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                                .addComponent(VidaOponenteText)
//                                .addGap(153, 153, 153)))
//                        .addGap(19, 19, 19))
//                    .addGroup(layout.createSequentialGroup()
//                        .addGap(23, 23, 23)
//                        .addComponent(Perso1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                        .addComponent(Perso2)
//                        .addGap(108, 108, 108))
//                    .addGroup(layout.createSequentialGroup()
//                        .addComponent(VidaBarra1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 239, Short.MAX_VALUE)
//                        .addComponent(VidaBarra2, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
//                        .addGap(30, 30, 30))))
//        );
//        layout.setVerticalGroup(
//            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
//                .addGap(31, 31, 31)
//                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                    .addComponent(SuaVidaText)
//                    .addComponent(VidaOponenteText))
//                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                    .addComponent(VidaBarra1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                    .addComponent(VidaBarra2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
//                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
//                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                    .addComponent(Perso1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
//                    .addGroup(layout.createSequentialGroup()
//                        .addGap(78, 78, 78)
//                        .addComponent(Perso2)))
//                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
//                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
//                        .addComponent(AtacarButton)
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                        .addComponent(FarmarButton)
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                        .addComponent(LojaButton)
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                        .addComponent(DesistirButton))
//                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
//                        .addComponent(Status)
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
//                        .addComponent(Ataque)
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
//                        .addComponent(Block)
//                        .addGap(18, 18, 18)
//                        .addComponent(Creditos)))
//                .addGap(19, 19, 19))
//        );
//
//        pack();
//    }// </editor-fold>//GEN-END:initComponents
//
//    private void AtacarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtacarButtonActionPerformed
//        // TODO add your handling code here:
//    }//GEN-LAST:event_AtacarButtonActionPerformed
//
//    private void FarmarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FarmarButtonActionPerformed
//        // TODO add your handling code here:
//    }//GEN-LAST:event_FarmarButtonActionPerformed
//
//    private void LojaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LojaButtonActionPerformed
//        // TODO add your handling code here:
//    }//GEN-LAST:event_LojaButtonActionPerformed
//
//    private void ServidorItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ServidorItemActionPerformed
//        // TODO add your handling code here:
//    }//GEN-LAST:event_ServidorItemActionPerformed
//
//    /**
//     * @param args the command line arguments
//     */
////    public static void main(String args[]) {
////        /* Set the Nimbus look and feel */
////        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
////        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
////         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
////         */
////        try {
////            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
////                if ("Nimbus".equals(info.getName())) {
////                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
////                    break;
////                }
////            }
////        } catch (ClassNotFoundException ex) {
////            java.util.logging.Logger.getLogger(TelaPrincipalDuel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
////        } catch (InstantiationException ex) {
////            java.util.logging.Logger.getLogger(TelaPrincipalDuel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
////        } catch (IllegalAccessException ex) {
////            java.util.logging.Logger.getLogger(TelaPrincipalDuel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
////        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
////            java.util.logging.Logger.getLogger(TelaPrincipalDuel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
////        }
////        //</editor-fold>
////
////        /* Create and display the form */
////        java.awt.EventQueue.invokeLater(new Runnable() {
////            public void run() {
////                new TelaPrincipalDuel().setVisible(true);
////            }
////        });
////    }
//
//    // Variables declaration - do not modify//GEN-BEGIN:variables
//    private javax.swing.JButton AtacarButton;
//    private javax.swing.JLabel Ataque;
//    private javax.swing.JLabel Block;
//    private javax.swing.JLabel Creditos;
//    private javax.swing.JMenuItem DesconectarItem;
//    private javax.swing.JButton DesistirButton;
//    private javax.swing.JButton FarmarButton;
//    protected javax.swing.JMenuItem iniciarPartida;
//    private javax.swing.JButton LojaButton;
//    private javax.swing.JMenu Menu;
//    private javax.swing.JLabel Perso1;
//    private javax.swing.JLabel Perso2;
//    protected javax.swing.JMenuItem ServidorItem;
//    private javax.swing.JLabel Status;
//    private javax.swing.JLabel SuaVidaText;
//    private javax.swing.JProgressBar VidaBarra1;
//    private javax.swing.JProgressBar VidaBarra2;
//    private javax.swing.JLabel VidaOponenteText;
//    private javax.swing.JMenu jMenu3;
//    private javax.swing.JMenuBar jMenuBar1;
//    // End of variables declaration//GEN-END:variables
//}
