/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package duelofarmslash;

import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import java.awt.Rectangle;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
/**
 *
 * @author kire
 */
public class TelaPrincipalDuel extends javax.swing.JFrame {
    protected AtorJogador ator;
    // Variables declaration - do not modify
    protected javax.swing.JButton AtacarButton;
    protected javax.swing.JLabel Ataque;
    protected javax.swing.JLabel Block;
    protected javax.swing.JLabel Creditos;
    protected javax.swing.JMenuItem DesconectarItem;
    protected javax.swing.JButton DesistirButton;
    protected javax.swing.JButton FarmarButton;
    protected javax.swing.JMenuItem iniciarPartida;
    protected javax.swing.JButton LojaButton;
    protected javax.swing.JMenu Menu;
    protected javax.swing.JLabel Perso1;
    protected javax.swing.JLabel Perso2;
    protected javax.swing.JMenuItem ServidorItem;
    protected javax.swing.JLabel Status;
    protected javax.swing.JLabel SuaVidaText;
    protected javax.swing.JProgressBar VidaBarra1;
    protected javax.swing.JProgressBar VidaBarra2;
    protected javax.swing.JLabel VidaOponenteText;
    protected javax.swing.JMenu jMenu3;
    protected javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration

    /**
     * Creates new form TelaPrincipalDuel
     */
    public TelaPrincipalDuel(final AtorJogador ator) {
        setTitle("Duelo - Farm and Slash");
        this.ator = ator;
        initComponents();
        this.setVisible(true);
        Perso1.setVisible(false);
        Perso2.setVisible(false);
    }


    public void notificar(String msg) {

        JOptionPane.showConfirmDialog(this, msg, "Atenção", JOptionPane.DEFAULT_OPTION, JOptionPane.PLAIN_MESSAGE);
            //JOptionPane.showMessageDialog(null, msg);
    }


    public String solicitar(String msg, String def) {
            return JOptionPane.showInputDialog(msg, def);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        AtacarButton = new javax.swing.JButton();
        FarmarButton = new javax.swing.JButton();
        LojaButton = new javax.swing.JButton();
        DesistirButton = new javax.swing.JButton();
        VidaBarra1 = new javax.swing.JProgressBar();
        VidaBarra2 = new javax.swing.JProgressBar();
        Status = new javax.swing.JLabel();
        Ataque = new javax.swing.JLabel();
        Block = new javax.swing.JLabel();
        Creditos = new javax.swing.JLabel();
        SuaVidaText = new javax.swing.JLabel();
        VidaOponenteText = new javax.swing.JLabel();
        Perso1 = new javax.swing.JLabel();
        Perso2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Menu = new javax.swing.JMenu();
        iniciarPartida = new javax.swing.JMenuItem();
        DesconectarItem = new javax.swing.JMenuItem();
        ServidorItem = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AtacarButton.setText("Atacar");
        AtacarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtacarButtonActionPerformed(evt);
            }
        });

        FarmarButton.setText("Farmar");
        FarmarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FarmarButtonActionPerformed(evt);
            }
        });

        LojaButton.setText("Loja");
        LojaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LojaButtonActionPerformed(evt);
            }
        });

        DesistirButton.setText("Desistir");

        Status.setText("Status");

        Ataque.setText("Ataque:");

        Block.setText("Block:");

        Creditos.setText("Creditos:");

        SuaVidaText.setText("Sua vida:");

        VidaOponenteText.setText("Oponente:");

        Perso1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/duelofarmslash/person1.gif"))); // NOI18N
        Perso2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/duelofarmslash/person2.gif"))); // NOI18N

        Menu.setText("Menu");
        // Iniciar partida
        iniciarPartida.setText("Iniciar partida");
        iniciarPartida.addActionListener(new java.awt.event.ActionListener(){
        public void actionPerformed(java.awt.event.ActionEvent e) {
                try {

                      ator.IniciarPartida();

                      iniciarPartida.setEnabled(false);

                     } catch (Exception e1) {
                        System.out.println("ex");
                        notificar(e1.getMessage());
                        e1.printStackTrace();
            }
        }
        });
        Menu.add(iniciarPartida);

        DesconectarItem.setText("Desconectar");
        DesconectarItem.addActionListener(new ActionListener(){
        public void actionPerformed(java.awt.event.ActionEvent e) {
            try {
                    ator.desconectar();
                    DesconectarItem.setEnabled(false);
                    ServidorItem.setEnabled(true);
                 //   reiniciar.setEnabled(false);
                    iniciarPartida.setEnabled(false);
                    notificar("Voce se desconectou da partida. A conexao foi encerrada");
            } catch (Exception ex) {
                    notificar(ex.getMessage());
                    ex.printStackTrace();
            }
      }
      });
        Menu.add(DesconectarItem);

        ServidorItem.setText("Conectar ao servidor");
        ServidorItem.addActionListener(new ActionListener(){
	         public void actionPerformed(java.awt.event.ActionEvent e) {
            try {
                    String servidor = solicitar("Insira o servidor:", "localhost");
                    String nomeJogador = solicitar("Insira seu nome:", null);
                    ator.conectar(nomeJogador, servidor);
                    iniciarPartida.setEnabled(true);
                    DesconectarItem.setEnabled(true);
                    ServidorItem.setEnabled(false);
                    notificar("A conexao foi estabelecida com sucesso.");
            } catch (Exception ex) {
                    notificar(ex.getMessage());
                    ex.printStackTrace();
            }
        }
        });
        Menu.add(ServidorItem);

        jMenuBar1.add(Menu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Status)
                                    .addComponent(Ataque)
                                    .addComponent(Block)
                                    .addComponent(Creditos))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(DesistirButton, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                                    .addComponent(LojaButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(AtacarButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(FarmarButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(SuaVidaText)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(VidaOponenteText)
                                .addGap(153, 153, 153)))
                        .addGap(19, 19, 19))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(Perso1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Perso2)
                        .addGap(108, 108, 108))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(VidaBarra1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 239, Short.MAX_VALUE)
                        .addComponent(VidaBarra2, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SuaVidaText)
                    .addComponent(VidaOponenteText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(VidaBarra1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VidaBarra2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Perso1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(Perso2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(AtacarButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FarmarButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LojaButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DesistirButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Status)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Ataque)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Block)
                        .addGap(18, 18, 18)
                        .addComponent(Creditos)))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AtacarButtonActionPerformed(java.awt.event.ActionEvent evt) {
      try {
        ator.realizaJogada();
        notificar("Você realizou o ataque");
      } catch (Exception ex) {
              notificar(ex.getMessage());
              ex.printStackTrace();
      }
    }

    private void FarmarButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void LojaButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void ServidorItemActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }


    }
